# Creating your 1st graph and running it in a session

In [1]:
import tensorflow as tf

x = tf.Variable(3, name="x")
y = tf.Variable(4, name="y")
f = x*x*y + y + 2

In [2]:
session = tf.Session()
session.run(x.initializer)
session.run(y.initializer)
result = session.run(f)
print(result)
session.close()

42


In [3]:
# To avoid repeating session.run()
with tf.Session() as session:
    x.initializer.run()
    y.initializer.run()
    result = f.eval()
result

42

In [4]:
# Avoid repeating initializer, use a global variable.
# It also initializes the variables.
init = tf.global_variables_initializer()
with tf.Session() as session:
    init.run()
    result = f.eval()
result

42

In [5]:
# Interactive session sets the actual session as a default session
session = tf.InteractiveSession()
init.run()
result = f.eval()
print(result)
session.close()

42


# Managing graphs

In [6]:
x1 = tf.Variable(3)
with tf.Session() as session:
    print(x1.graph is tf.get_default_graph())

True


In [7]:
graph = tf.Graph()
with graph.as_default():
    x2 = tf.Variable(1)
    print(x2.graph is graph)
print(x2.graph is tf.get_default_graph())

True
False


# Lifecycle of a Node Value

In [8]:
# tf makes two calls to w & x
w = tf.constant(3)
x = w + 2
y = x + 5
z = x * 3

with tf.Session() as session:
    print(y.eval())
    print(z.eval())

10
15


In [9]:
# Evaluate both expression to execute w & x once
with tf.Session() as session:
    y_val, z_val = session.run([y, z])
    print(y_val)
    print(z_val)

10
15


# Linear Regression with TensorFlow

In [10]:
import numpy as np
from sklearn.datasets import fetch_california_housing

housing = fetch_california_housing()
m, n = housing.data.shape
housing_data_plus_bias = np.c_[np.ones((m, 1)), housing.data]

X = tf.constant(housing_data_plus_bias, dtype=tf.float32, name="X")
y = tf.constant(housing.target.reshape(-1, 1), dtype=tf.float32, name="y")
XT = tf.transpose(X)
theta = tf.matmul(tf.matmul(tf.matrix_inverse(tf.matmul(XT, X)), XT), y)

with tf.Session() as session:
    thetha_value = theta.eval()
print(thetha_value.shape)

(9, 1)


# Implementing Gradient Descent

## Manually computing the gradients

In [11]:
def reset_graph(seed=42):
    tf.reset_default_graph()
    tf.set_random_seed(seed)
    np.random.seed(seed)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_housing_data = scaler.fit_transform(housing.data)
scaled_housing_data_plus_bias = np.c_[np.ones((m, 1)), scaled_housing_data]

In [12]:
reset_graph()
n_epochs = 1000
learning_rate = 0.01

X = tf.constant(scaled_housing_data_plus_bias, dtype=tf.float32, name="X")
y = tf.constant(housing.target.reshape(-1, 1), dtype=tf.float32, name="y")
theta = tf.Variable(tf.random_uniform([n + 1, 1], -1.0, 1.0), name="theta")
y_pred = tf.matmul(X, theta, name="predictions")
error = y_pred - y
mse = tf.reduce_mean(tf.square(error), name="mse")
gradients = 2/m * tf.matmul(tf.transpose(X), error)
training_op = tf.assign(theta, theta - learning_rate * gradients)

init = tf.global_variables_initializer()

with tf.Session() as session:
    session.run(init)
    
    for epoch in range(n_epochs):
        if epoch % 100 == 0:
            print ("Epoch", epoch, "MSE = ", mse.eval())
        session.run(training_op)
    best_theta = theta.eval()

Epoch 0 MSE =  12.408
Epoch 100 MSE =  0.755197
Epoch 200 MSE =  0.542087
Epoch 300 MSE =  0.53317
Epoch 400 MSE =  0.530538
Epoch 500 MSE =  0.528797
Epoch 600 MSE =  0.527548
Epoch 700 MSE =  0.52665
Epoch 800 MSE =  0.526001
Epoch 900 MSE =  0.525533


## Using autodiff

In [13]:
## autodiff simplifies the computation of gradients
reset_graph()
n_epochs = 1000
learning_rate = 0.01

X = tf.constant(scaled_housing_data_plus_bias, dtype=tf.float32, name="X")
y = tf.constant(housing.target.reshape(-1, 1), dtype=tf.float32, name="y")
theta = tf.Variable(tf.random_uniform([n + 1, 1], -1.0, 1.0), name="theta")
y_pred = tf.matmul(X, theta, name="predictions")
error = y_pred - y
mse = tf.reduce_mean(tf.square(error), name="mse")
gradients = tf.gradients(mse, [theta])[0] # Using autodiff feature for the previous example.
training_op = tf.assign(theta, theta - learning_rate * gradients)

init = tf.global_variables_initializer()

with tf.Session() as session:
    session.run(init)
    
    for epoch in range(n_epochs):
        if epoch % 100 == 0:
            print ("Epoch", epoch, "MSE = ", mse.eval())
        session.run(training_op)
    best_theta = theta.eval()

Epoch 0 MSE =  12.408
Epoch 100 MSE =  0.755197
Epoch 200 MSE =  0.542087
Epoch 300 MSE =  0.53317
Epoch 400 MSE =  0.530538
Epoch 500 MSE =  0.528797
Epoch 600 MSE =  0.527548
Epoch 700 MSE =  0.52665
Epoch 800 MSE =  0.526001
Epoch 900 MSE =  0.525533


## Using an Optimizer

In [14]:
# TF also has some optimizers, including one for GradiendDescent. 
# This is good bc it allows to try other optimizers with model, 
# instead of implement everything. E.g. MomentumOptimizer
reset_graph()
n_epochs = 1000
learning_rate = 0.01

X = tf.constant(scaled_housing_data_plus_bias, dtype=tf.float32, name="X")
y = tf.constant(housing.target.reshape(-1, 1), dtype=tf.float32, name="y")
theta = tf.Variable(tf.random_uniform([n + 1, 1], -1.0, 1.0), name="theta")
y_pred = tf.matmul(X, theta, name="predictions")
error = y_pred - y
mse = tf.reduce_mean(tf.square(error), name="mse")
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate) # Gradiend descent optimizer
training_op = optimizer.minimize(mse)

init = tf.global_variables_initializer()

with tf.Session() as session:
    session.run(init)
    
    for epoch in range(n_epochs):
        if epoch % 100 == 0:
            print ("Epoch", epoch, "MSE = ", mse.eval())
        session.run(training_op)
    best_theta = theta.eval()

Epoch 0 MSE =  12.408
Epoch 100 MSE =  0.755197
Epoch 200 MSE =  0.542087
Epoch 300 MSE =  0.53317
Epoch 400 MSE =  0.530538
Epoch 500 MSE =  0.528797
Epoch 600 MSE =  0.527548
Epoch 700 MSE =  0.52665
Epoch 800 MSE =  0.526001
Epoch 900 MSE =  0.525533


# Feeding Data to the Training algorithm

In [15]:
# A placeholder is only used to output data. They do not perform computations
A = tf.placeholder(tf.float32, shape=(None, 3))
B = A + 5

with tf.Session() as sess:
    B_val_1 = B.eval(feed_dict={A: [[1, 2, 3]]})
    B_val_2 = B.eval(feed_dict={A: [[4, 5, 6], [7, 8, 9]]})
print(B_val_1)
print(B_val_2)

[[ 6.  7.  8.]]
[[  9.  10.  11.]
 [ 12.  13.  14.]]


## Implementing mini batch gradient descent


In [16]:
reset_graph()
n_epochs = 1000
learning_rate = 0.01
batch_size = 100
n_batches = int(np.ceil(m / batch_size))

X = tf.placeholder(tf.float32, shape=[None, n + 1], name="X")
y = tf.placeholder(tf.float32, shape=[None, 1], name="y")
theta = tf.Variable(tf.random_uniform([n + 1, 1], -1.0, 1.0), name="theta")
y_pred = tf.matmul(X, theta, name="predictions")
error = y_pred - y
mse = tf.reduce_mean(tf.square(error), name="mse")
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate) # Gradiend descent optimizer
training_op = optimizer.minimize(mse)

def fetch_batch(epoch, batch_index, batch_size):
    np.random.seed(epoch * n_batches + batch_index)
    indices = np.random.randint(m, size=batch_size)
    X_batch = scaled_housing_data_plus_bias[indices]
    y_batch = housing.target.reshape(-1, 1)[indices]
    return X_batch, y_batch

init = tf.global_variables_initializer()

with tf.Session() as session:
    session.run(init)
    
    for epoch in range(n_epochs):
        for batch_index in range(n_batches):
            X_batch, y_batch = fetch_batch(epoch, batch_index, batch_size)
            session.run(training_op, feed_dict={X: X_batch, y: y_batch})
    best_theta = theta.eval()
best_theta

array([[ 2.07144761],
       [ 0.84620118],
       [ 0.11558535],
       [-0.26835832],
       [ 0.32982782],
       [ 0.00608358],
       [ 0.07052915],
       [-0.87988573],
       [-0.86342508]], dtype=float32)

# Saving and restoring models

_save()_ method also saves the structure of the graph in a second file with the same name plus a .meta extension.


In [20]:
reset_graph()
n_epochs = 1000
learning_rate = 0.01

X = tf.constant(scaled_housing_data_plus_bias, dtype=tf.float32, name="X")
y = tf.constant(housing.target.reshape(-1, 1), dtype=tf.float32, name="y")
theta = tf.Variable(tf.random_uniform([n + 1, 1], -1.0, 1.0), name="theta")
y_pred = tf.matmul(X, theta, name="predictions")
error = y_pred - y
mse = tf.reduce_mean(tf.square(error), name="mse")
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate) # Gradiend descent optimizer
training_op = optimizer.minimize(mse)

init = tf.global_variables_initializer()

In [25]:
# Saving a model
saver = tf.train.Saver()

with tf.Session() as session:
    session.run(init)
    
    for epoch in range(n_epochs):
        if epoch % 100 == 0: # checkpoint every 100 epochs
            save_path = saver.save(session, "mytf_model.cpkt")
            
        session.run(training_op)
    best_theta = theta.eval()
    save_path = saver.save(session, "mytf_model_final.cpkt")

In [32]:
# Restoring model
saver = tf.train.Saver()

with tf.Session() as session:
    saver.restore(session, "mytf_model_final.cpkt")

INFO:tensorflow:Restoring parameters from mytf_model_final.cpkt


# Visualizing the Graph and Training Curves using TensorBoard